# Sunil Narayan - CORGIS State Crime Dataset Update

In [77]:
import pandas as pd
import numpy as np

In [78]:
addingFrame = pd.read_csv("estimated_crimes_1979_2019.csv")

In [79]:
addingFrame.head()

,year,state_abbr,state_name,population,violent_crime,homicide,rape_legacy,rape_revised,robbery,aggravated_assault,property_crime,burglary,larceny,motor_vehicle_theft,caveats
0,1979,NaN,NaN,220099000,1208030,21460,76390.0,NaN,480700,629480,11041500,3327700,6601000,1112800,NaN
1,1979,AK,Alaska,406000,1994,54,292.0,NaN,445,1203,23193,5616,15076,2501,NaN
2,1979,AL,Alabama,3769000,15578,496,1037.0,NaN,4127,9918,144372,48517,83791,12064,NaN
3,1979,AR,Arkansas,2180000,7984,198,595.0,NaN,1626,5565,70949,21457,45267,4225,NaN
4,1979,AZ,Arizona,2450000,14528,219,1120.0,NaN,4305,8884,177977,48916,116976,12085,NaN

In [80]:
stateFrame= pd.read_csv("state_crime.csv")

In [81]:
stateFrame.head()

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
0,Alabama,1960,3266740,1035.4,355.9,592.1,87.3,186.6,138.1,12.4,...,27.5,33823,11626,19344,2853,6097,4512,406,281,898
1,Alabama,1961,3302000,985.5,339.3,569.4,76.8,168.5,128.9,12.9,...,19.1,32541,11205,18801,2535,5564,4255,427,252,630
2,Alabama,1962,3358000,1067.0,349.1,634.5,83.4,157.3,119.0,9.4,...,22.5,35829,11722,21306,2801,5283,3995,316,218,754
3,Alabama,1963,3347000,1150.9,376.9,683.4,90.6,182.7,142.1,10.2,...,24.7,38521,12614,22874,3033,6115,4755,340,192,828
4,Alabama,1964,3407000,1358.7,466.6,784.1,108.0,213.1,163.0,9.3,...,29.1,46290,15898,26713,3679,7260,5555,316,397,992

In [82]:
addingFrame.rename(columns = {"state_name":"State", "population":"Data.Population"}, inplace = True )

In [83]:
addingFrame.columns

Index(['year', 'state_abbr', 'State', 'Data.Population', 'violent_crime',
       'homicide', 'rape_legacy', 'rape_revised', 'robbery',
       'aggravated_assault', 'property_crime', 'burglary', 'larceny',
       'motor_vehicle_theft', 'caveats'],
      dtype='object')

In [84]:
mergeFrame = addingFrame.loc[:, ['year', 'State', 'Data.Population', 'violent_crime',
       'homicide', 'rape_legacy', 'rape_revised', 'robbery',
       'aggravated_assault', 'property_crime', 'burglary', 'larceny',
       'motor_vehicle_theft']]

In [85]:
stateFrame.columns

Index(['State', 'Year', 'Data.Population', 'Data.Rates.Property.All',
       'Data.Rates.Property.Burglary', 'Data.Rates.Property.Larceny',
       'Data.Rates.Property.Motor', 'Data.Rates.Violent.All',
       'Data.Rates.Violent.Assault', 'Data.Rates.Violent.Murder',
       'Data.Rates.Violent.Rape', 'Data.Rates.Violent.Robbery',
       'Data.Totals.Property.All', 'Data.Totals.Property.Burglary',
       'Data.Totals.Property.Larceny', 'Data.Totals.Property.Motor',
       'Data.Totals.Violent.All', 'Data.Totals.Violent.Assault',
       'Data.Totals.Violent.Murder', 'Data.Totals.Violent.Rape',
       'Data.Totals.Violent.Robbery'],
      dtype='object')

In [86]:
mergeFrame = mergeFrame.rename(columns = {"year":"Year", "homicide":"Data.Totals.Violent.Murder", "rape_legacy":"Data.Totals.Violent.Rape", "rape_revised":"Data.Totals.Violent.RapeR", "Robbery":"Data.Totals.Violent.Robbery", "aggravated_assault":"Data.Totals.Violent.Assault", "property_crime":"Data.Totals.Property.All", "burglary":"Data.Totals.Property.Burglary", "larceny":"Data.Totals.Property.Larceny", "motor_vehicle_theft":"Data.Totals.Property.Motor", "robbery":"Data.Totals.Violent.Robbery", "violent_crime":"Data.Totals.Violent.All"})

In [87]:
mergeFrame.State = mergeFrame.State.replace(to_replace = np.NaN, value = "United States")

In [88]:
mergeFrame = mergeFrame.replace(to_replace = np.NaN, value = 0)

In [89]:
mergeFrame = mergeFrame[mergeFrame.Year>=2013]

In [90]:
mergeFrame["Data.Totals.Violent.Rape"] = mergeFrame["Data.Totals.Violent.Rape"]+mergeFrame["Data.Totals.Violent.RapeR"]

In [91]:
mergeFrame = mergeFrame.drop(columns = "Data.Totals.Violent.RapeR")

In [92]:
rateModifier = 100000/mergeFrame["Data.Population"]

In [93]:
rateValues = pd.DataFrame({"State":mergeFrame.State, "Year":mergeFrame.Year, "Data.Rates.Property.All":(mergeFrame["Data.Totals.Property.All"]*rateModifier), "Data.Rates.Property.Burglary":(mergeFrame["Data.Totals.Property.Burglary"]*rateModifier), "Data.Rates.Property.Larceny":(mergeFrame["Data.Totals.Property.Larceny"]*rateModifier),"Data.Rates.Property.Motor":(mergeFrame["Data.Totals.Property.Motor"]*rateModifier),"Data.Rates.Violent.All":(mergeFrame["Data.Totals.Violent.All"]*rateModifier),"Data.Rates.Violent.Assault":(mergeFrame["Data.Totals.Violent.Assault"]*rateModifier),"Data.Rates.Violent.Murder":(mergeFrame["Data.Totals.Violent.Murder"]*rateModifier),"Data.Rates.Violent.Rape":(mergeFrame["Data.Totals.Violent.Rape"]*rateModifier),"Data.Rates.Violent.Robbery":(mergeFrame["Data.Totals.Violent.Robbery"]*rateModifier)})

In [94]:
rateValues.head()

,State,Year,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,Data.Rates.Violent.Rape,Data.Rates.Violent.Robbery
1752,United States,2013,2733.636491,610.475220,1901.899513,221.261758,369.133369,229.631175,4.524206,61.865885,109.034974
1753,Alaska,2013,2877.007944,395.654716,2251.447592,229.905637,638.717194,424.138600,4.611676,214.578594,84.502190
1754,Alabama,2013,3347.851343,877.327991,2252.008483,218.514868,430.989186,285.229860,7.157639,72.486614,96.090274
1755,Arkansas,2013,3598.697430,1026.407978,2380.385059,191.904393,463.200018,331.084084,5.340066,88.719449,76.417019
1756,Arizona,2013,3365.397151,727.837556,2381.854883,255.704712,415.614355,262.110141,5.350417,83.165072,100.316549

In [95]:
rateValues.shape

(364, 11)

In [96]:
mergeFrame.shape

(364, 12)

In [97]:
finalMergeFrame = pd.merge(mergeFrame, rateValues)

In [98]:
finalMergeFrame.tail()

,Year,State,Data.Population,Data.Totals.Violent.All,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery,Data.Totals.Violent.Assault,Data.Totals.Property.All,Data.Totals.Property.Burglary,...,Data.Totals.Property.Motor,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,Data.Rates.Violent.Rape,Data.Rates.Violent.Robbery
359,2019,Washington,7614893,22377,198,3332.0,5147,13700,204224,34540,...,24402,2681.902425,453.584837,1907.866598,320.450990,293.858364,179.910604,2.600168,43.756360,67.591232
360,2019,Wisconsin,5822434,17070,175,2261.0,2991,11643,85672,12667,...,7385,1471.412128,217.555064,1127.020074,126.836989,293.176359,199.967917,3.005616,38.832557,51.370269
361,2019,West Virginia,1792147,5674,78,754.0,378,4464,28376,5891,...,2419,1583.352258,328.711875,1119.662617,134.977767,316.603493,249.086710,4.352322,42.072442,21.092020
362,2019,Wyoming,578759,1258,13,324.0,67,854,9093,1396,...,713,1571.120276,241.205752,1206.719896,123.194629,217.361631,147.557101,2.246185,55.981851,11.576494
363,2019,United States,328239523,1245410,16425,139815.0,267988,821182,6925677,1117696,...,721885,2109.946096,340.512315,1549.507492,219.926288,379.421097,250.177673,5.003968,42.595419,81.644038

In [99]:
stateFrame.shape

(2751, 21)

In [100]:
finalMergeFrame.shape

(364, 21)

In [101]:
completedSet = stateFrame.append(finalMergeFrame)

In [102]:
completedSet.tail()

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
359,Washington,2019,7614893,2681.902425,453.584837,1907.866598,320.450990,293.858364,179.910604,2.600168,...,67.591232,204224,34540,145282,24402,22377,13700,198,3332.0,5147
360,Wisconsin,2019,5822434,1471.412128,217.555064,1127.020074,126.836989,293.176359,199.967917,3.005616,...,51.370269,85672,12667,65620,7385,17070,11643,175,2261.0,2991
361,West Virginia,2019,1792147,1583.352258,328.711875,1119.662617,134.977767,316.603493,249.086710,4.352322,...,21.092020,28376,5891,20066,2419,5674,4464,78,754.0,378
362,Wyoming,2019,578759,1571.120276,241.205752,1206.719896,123.194629,217.361631,147.557101,2.246185,...,11.576494,9093,1396,6984,713,1258,854,13,324.0,67
363,United States,2019,328239523,2109.946096,340.512315,1549.507492,219.926288,379.421097,250.177673,5.003968,...,81.644038,6925677,1117696,5086096,721885,1245410,821182,16425,139815.0,267988

In [103]:
completedSet

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
0,Alabama,1960,3266740,1035.400000,355.900000,592.100000,87.300000,186.600000,138.100000,12.400000,...,27.500000,33823,11626,19344,2853,6097,4512,406,281.0,898
1,Alabama,1961,3302000,985.500000,339.300000,569.400000,76.800000,168.500000,128.900000,12.900000,...,19.100000,32541,11205,18801,2535,5564,4255,427,252.0,630
2,Alabama,1962,3358000,1067.000000,349.100000,634.500000,83.400000,157.300000,119.000000,9.400000,...,22.500000,35829,11722,21306,2801,5283,3995,316,218.0,754
3,Alabama,1963,3347000,1150.900000,376.900000,683.400000,90.600000,182.700000,142.100000,10.200000,...,24.700000,38521,12614,22874,3033,6115,4755,340,192.0,828
4,Alabama,1964,3407000,1358.700000,466.600000,784.100000,108.000000,213.100000,163.000000,9.300000,...,29.100000,46290,15898,26713,3679,7260,5555,316,397.0,992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,Washington,2019,7614893,2681.902425,453.584837,1907.866598,320.450990,293.858364,179.910604,2.600168,...,67.591232,204224,34540,145282,24402,22377,13700,198,3332.0,5147
360,Wisconsin,2019,5822434,1471.412128,217.555064,1127.020074,126.836989,293.176359,199.967917,3.005616,...,51.370269,85672,12667,65620,7385,17070,11643,175,2261.0,2991
361,West Virginia,2019,1792147,1583.352258,328.711875,1119.662617,134.977767,316.603493,249.086710,4.352322,...,21.092020,28376,5891,20066,2419,5674,4464,78,754.0,378
362,Wyoming,2019,578759,1571.120276,241.205752,1206.719896,123.194629,217.361631,147.557101,2.246185,...,11.576494,9093,1396,6984,713,1258,854,13,324.0,67
363,United States,2019,328239523,2109.946096,340.512315,1549.507492,219.926288,379.421097,250.177673,5.003968,...,81.644038,6925677,1117696,5086096,721885,1245410,821182,16425,139815.0,267988

In [130]:
completedSet = completedSet.sort_values(by=["State", "Year"])

In [131]:
completedSet.to_csv("State Crime Updated through 2019")